import type { JSX } from 'react'
import {
    BiBarChartAlt, BiBookBookmark, BiBookOpen,
    BiBookReader, BiCodeAlt,
    BiCodeBlock, BiCodeCurly, BiCommand, BiCubeAlt, BiDetail, BiDownload, BiFileBlank, BiGridAlt, BiHome, BiInfoCircle, BiLayer, BiPlusCircle, BiQuestionMark, BiShieldAlt2, BiSitemap, BiSolidHand, BiTask, BiTestTube
} from 'react-icons/bi'
import { BsInfoCircle } from 'react-icons/bs'
import { CiVault } from 'react-icons/ci'
import { GiRadarSweep } from 'react-icons/gi'
import { GoLaw } from 'react-icons/go'
import { GrGroup, GrValidate } from 'react-icons/gr'
import { HiOutlineBuildingLibrary } from 'react-icons/hi2'
import { LuMonitor } from 'react-icons/lu'
import {
    PiBoneDuotone,
    PiBookDuotone,
    PiBreadDuotone,
    PiBrowsersDuotone,
    PiCalendarCheckDuotone,
    PiCalendarDuotone,
    PiCardsDuotone,
    PiCaretCircleDownDuotone,
    PiChalkboardSimpleDuotone,
    PiChartBarDuotone,
    PiChartDonutDuotone,
    PiChartLineUpDuotone,
    PiChartPieSliceDuotone,
    PiChatCenteredDotsDuotone,
    PiChatCenteredDuotone,
    PiChatCircleDuotone,
    PiChatDotsDuotone,
    PiCheckSquareDuotone,
    PiCircleHalfTiltDuotone,
    PiClipboardTextDuotone,
    PiClockAfternoonDuotone,
    PiClockCountdownDuotone,
    PiCodeDuotone,
    PiCodeSimpleDuotone,
    PiCompassDuotone,
    PiCurrencyCircleDollarDuotone,
    PiCursorClickDuotone,
    PiDesktopDuotone,
    PiDotsThreeCircleDuotone,
    PiEnvelopeDuotone,
    PiFileMagnifyingGlassDuotone,
    PiFileTextDuotone,
    PiFilmScriptDuotone,
    PiFolderOpenDuotone,
    PiFootprintsDuotone,
    PiGearDuotone,
    PiGridFourDuotone,
    PiHandWithdrawDuotone,
    PiHeadsetDuotone,
    PiHouseLineDuotone,
    PiImagesDuotone,
    PiKeyDuotone,
    PiKeyholeDuotone,
    PiLightbulbDuotone,
    PiListChecksBold,
    PiListChecksDuotone,
    PiListDuotone,
    PiListMagnifyingGlassDuotone,
    PiListPlusDuotone,
    PiListStarDuotone,
    PiLockKeyOpenDuotone,
    PiMapTrifoldDuotone,
    PiMedalDuotone,
    PiMegaphoneDuotone,
    PiNewspaperDuotone,
    PiNotePencilDuotone,
    PiPackageDuotone,
    PiPasswordDuotone,
    PiPencilSimpleLineDuotone,
    PiPlusSquareDuotone,
    PiProjectorScreenChartDuotone,
    PiPuzzlePieceDuotone,
    PiQuotesDuotone,
    PiRadioButtonDuotone,
    PiRocketDuotone,
    PiRowsDuotone,
    PiRowsPlusBottomDuotone,
    PiShareNetworkDuotone,
    PiShieldCheckDuotone,
    PiShoppingCartDuotone,
    PiShoppingCartSimpleDuotone,
    PiSparkleDuotone,
    PiSpeedometerDuotone,
    PiSpinnerBallDuotone,
    PiSpinnerGapDuotone,
    PiStackPlusDuotone,
    PiSwatchesDuotone,
    PiTableDuotone,
    PiTagDuotone,
    PiTextAaDuotone,
    PiTextIndentDuotone,
    PiToggleRightDuotone,
    PiToolboxDuotone,
    PiUploadDuotone,
    PiUserCircleDuotone,
    PiUserGearDuotone,
    PiUserListDuotone,
    PiUserPlusDuotone,
    PiUsersDuotone,
    PiWarningDuotone,
} from 'react-icons/pi'
import { TbBrandAo3 } from 'react-icons/tb'
import { TfiHelpAlt } from 'react-icons/tfi'
export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    'common': <PiSwatchesDuotone />,
    'ui-components': <PiPuzzlePieceDuotone />,
    'ui-common-button': <PiCursorClickDuotone />,
    'ui-common-grid': <PiGridFourDuotone />,
    'ui-common-typography': <PiTextAaDuotone />,
    'ui-common-icons': <PiImagesDuotone />,
    'feedback': <PiChatDotsDuotone />,
    'ui-feedback-alert': <PiWarningDuotone />,
    'ui-feedback-dialog': <PiChatCircleDuotone />,
    'ui-feedback-drawer': <PiHandWithdrawDuotone />,
    'ui-feedback-progress': <PiSpinnerGapDuotone />,
    'ui-feedback-skeleton': <PiBoneDuotone />,
    'ui-feedback-spinner': <PiSpinnerBallDuotone />,
    'ui-feedback-toast': <PiBreadDuotone />,
    'data-display': <PiDesktopDuotone />,
    'ui-data-display-avatar': <PiUserCircleDuotone />,
    'ui-data-display-badge': <PiMedalDuotone />,
    'ui-data-display-calendar': <PiCalendarDuotone />,
    'ui-data-display-card': <PiCardsDuotone />,
    'ui-data-display-table': <PiTableDuotone />,
    'ui-data-display-tag': <PiTagDuotone />,
    'ui-data-display-timeline': <PiClockCountdownDuotone />,
    'ui-data-display-tooltip': <PiChatCenteredDuotone />,
    'forms': <PiFileTextDuotone />,
    'ui-forms-checkbox': <PiCheckSquareDuotone />,
    'ui-forms-datepicker': <PiCalendarCheckDuotone />,
    'ui-forms-form-control': <PiClipboardTextDuotone />,
    'ui-forms-input': <PiRowsDuotone />,
    'ui-forms-input-group': <PiRowsPlusBottomDuotone />,
    'ui-forms-radio': <PiRadioButtonDuotone />,
    'ui-forms-segment': <PiChartDonutDuotone />,
    'ui-forms-select': <PiListChecksBold />,
    'ui-forms-switcher': <PiToggleRightDuotone />,
    'ui-forms-time-picker': <PiClockAfternoonDuotone />,
    'ui-forms-upload': <PiUploadDuotone />,
    'navigation': <PiCompassDuotone />,
    'ui-navigation-dropdown': <PiCaretCircleDownDuotone />,
    'ui-navigation-menu': <PiListDuotone />,
    'ui-navigation-pagination': <PiCodeSimpleDuotone />,
    'ui-navigation-steps': <PiFootprintsDuotone />,
    'ui-navigation-tabs': <PiBrowsersDuotone />,
    'graph': <PiChartPieSliceDuotone />,
    'ui-graph-chart': <PiChartLineUpDuotone />,
    'ui-graph-maps': <PiMapTrifoldDuotone />,
    'concepts': <PiLightbulbDuotone />,
    'customers': <PiUsersDuotone />,
    'customer-list': <PiUserListDuotone />,
    'customer-edit': <PiPencilSimpleLineDuotone />,
    'customer-create': <PiUserPlusDuotone />,
    'customer-details': <PiUserCircleDuotone />,
    'products': <PiPackageDuotone />,
    'product-list': <PiListStarDuotone />,
    'product-edit': <PiNotePencilDuotone />,
    'product-create': <PiPlusSquareDuotone />,
    'projects': <PiProjectorScreenChartDuotone />,
    'project-scrum-board': <PiChalkboardSimpleDuotone />,
    'project-list': <PiListChecksDuotone />,
    'project-details': <PiFileMagnifyingGlassDuotone />,
    'project-task': <PiCalendarCheckDuotone />,
    'project-issue': <PiWarningDuotone />,
    'orders': <PiShoppingCartDuotone />,
    'order-list': <PiListPlusDuotone />,
    'order-edit': <PiFilmScriptDuotone />,
    'order-details': <PiListMagnifyingGlassDuotone />,
    'order-create': <PiStackPlusDuotone />,
    'calendar': <PiCalendarDuotone />,
    'file-manager': <PiFolderOpenDuotone />,
    'mail': <PiEnvelopeDuotone />,
    'account': <PiUserCircleDuotone />,
    'account-settings': <PiGearDuotone />,
    'account-activity-logs': <PiFileTextDuotone />,
    'account-role-and-permission': <PiUserGearDuotone />,
    'account-pricing': <PiCurrencyCircleDollarDuotone />,
    'ai': <PiSparkleDuotone />,
    'ai-chat': <PiChatCenteredDotsDuotone />,
    'ai-image': <PiImagesDuotone />,
    'chat': <PiChatCircleDuotone />,
    'help-center': <TfiHelpAlt />,
    'help-ceter-support-hub': <PiHeadsetDuotone />,
    'help-ceter-article': <PiNewspaperDuotone />,
    'help-ceter-edit-article': <PiTextIndentDuotone />,
    'help-ceter-manage-article': <PiQuotesDuotone />,
    'authentication': <PiShieldCheckDuotone />,
    'sign-in': <PiKeyDuotone />,
    'sign-up': <PiUserPlusDuotone />,
    'forgot-password': <PiLockKeyOpenDuotone />,
    'reset-password': <PiKeyholeDuotone />,
    'otp-verification': <PiPasswordDuotone />,
    'dashboard': <PiSpeedometerDuotone />,
    'dashboard-ecommerce': <PiShoppingCartSimpleDuotone />,
    'dashboard-project': <PiRocketDuotone />,
    'dashboard-analytic': <PiChartBarDuotone />,
    'dashboard-marketing': <PiMegaphoneDuotone />,
    'others': <PiDotsThreeCircleDuotone />,
    'access-denied': <PiCircleHalfTiltDuotone />,
    'landing': <PiHouseLineDuotone />,
    'documentation': <PiBookDuotone />,
    'shared-component-doc': <PiShareNetworkDuotone />,
    'utils-doc': <PiToolboxDuotone />,
    'change-log': <PiCodeDuotone />,
    'about': <BsInfoCircle />,
    'law': <GoLaw />,
    'vaults': <CiVault />,
    'monitors': <LuMonitor />,
    'validators': <GrValidate />,
    'dao': <TbBrandAo3 />,
    'universal': <BiFileBlank />,
    'home-icon': <BiHome />,
    'vaults-icon': <BiShieldAlt2 />,
    'monitors-icon': <GiRadarSweep />,
    'validators-icon': <BiTestTube />,
    'dao-icon': <HiOutlineBuildingLibrary />,
    'legal-icon': <BiShieldAlt2 />,
    'documentation-icon': <BiBookBookmark />,
    'help-center-icon': <BiQuestionMark />,
    'about-icon': <BiInfoCircle />,

    // Sub-menu items
    'create-icon': <BiPlusCircle />,
    'status-icon': <BiTask />,
    'network-icon': <BiSitemap />,
    'statistics-icon': <BiBarChartAlt />,
    'dashboard-icon': <BiGridAlt />,
    'voting-icon': <BiSolidHand />,
    'tests-icon': <BiTestTube />,
    'structure-icon': <BiCubeAlt />,
    'governance-icon': <GrGroup />,
    'installation-icon': <BiDownload />,
    'protocol-icon': <BiCommand />,
    'privacy-icon': <BiShieldAlt2 />,
    'api-icon': <BiCodeAlt />,
    'sdk-icon': <BiCodeBlock />,
    'tutorial-icon': <BiBookOpen />,
    'userguide-icon': <BiBookReader />,
    'faq-icon': <BiQuestionMark />,
    'examples-icon': <BiDetail />,
    'usecases-icon': <BiLayer />,
    'zuzdsl-icon': <BiCodeCurly />,
}

export default navigationIcon
