// pub mod asset_derivation; // DEPRECATED: tested derive_asset_hash() which was removed in v1.134.0
#[path = "test_assets_amount.rs"]
pub mod amount;
#[path = "test_assets_signature_domain.rs"]
pub mod asset_signature_domain;
#[path = "test_assets_batch_range_proofs.rs"]
pub mod batch_range_proofs;
#[cfg(feature = "deterministic-rng")]
#[path = "test_assets_commitment_balance.rs"]
pub mod commitment_balance;
#[path = "test_assets_commitment_homomorphism.rs"]
pub mod commitment_homomorphism;
#[path = "test_assets_concurrent_creation.rs"]
pub mod concurrent_creation;
#[path = "test_assets_config_integration.rs"]
pub mod config_integration;
#[path = "test_assets_creation_performance.rs"]
pub mod creation_performance;
#[path = "test_assets_cross_asset_operations.rs"]
pub mod cross_asset_operations;
#[path = "test_assets_crypto_integration.rs"]
pub mod crypto_integration;
#[path = "test_assets_definition_arc.rs"]
pub mod definition_arc;
#[path = "test_assets_error_handling.rs"]
pub mod error_handling;
#[cfg(feature = "deterministic-rng")]
#[path = "test_assets_fee_balance.rs"]
pub mod fee_balance;
#[path = "test_assets_fixtures.rs"]
pub mod fixtures;
#[cfg(feature = "deterministic-rng")]
#[path = "test_assets_full_transaction_workflow.rs"]
pub mod full_transaction_workflow;
#[path = "test_assets_genesis_creation.rs"]
pub mod genesis_creation;
#[path = "test_assets_logger_integration.rs"]
pub mod logger_integration;
#[path = "test_assets_long_running_memory.rs"]
pub mod long_running_memory;
#[path = "test_assets_metadata_limits.rs"]
pub mod metadata_limits;
#[path = "test_assets_nonce_counter.rs"]
pub mod nonce_counter;
#[path = "test_assets_nonce_uniqueness.rs"]
pub mod nonce_uniqueness;
#[path = "test_assets_owner_signature_security.rs"]
pub mod owner_signature_security;
#[path = "test_assets_proof_size_limits.rs"]
pub mod proof_size_limits;
#[path = "test_assets_property_based.rs"]
pub mod property_based;
#[path = "test_assets_range_proof_generation.rs"]
pub mod range_proof_generation;
#[path = "test_assets_range_proof_soundness.rs"]
pub mod range_proof_soundness;
#[path = "test_assets_registry_concurrent_reads.rs"]
pub mod registry_concurrent_reads;
#[path = "test_assets_registry_integration.rs"]
pub mod registry_integration;
#[path = "test_assets_registry_snapshot_updates.rs"]
pub mod registry_snapshot_updates;
#[path = "test_assets_registry_stress.rs"]
pub mod registry_stress;
#[path = "test_rights_config.rs"]
pub mod rights_config;
#[path = "test_assets_secret.rs"]
pub mod secret;
#[path = "test_assets_serial_id_encoding.rs"]
pub mod serial_id_encoding;
#[path = "test_assets_wallet_recovery.rs"]
pub mod wallet_recovery;
#[path = "test_assets_wire_format_snapshots.rs"]
pub mod wire_format_snapshots;
#[path = "test_assets_wire_pkg_bounds.rs"]
pub mod wire_pkg_bounds;
#[path = "test_assets_wire_registration.rs"]
pub mod wire_registration;
