pub const CONS_DOMAINS: &[&[u8]] = &[
    b"z00z.consensus.receiver_id.v1",
    b"z00z.consensus.view_key.v1",
    b"Z00Z/IDENTITY",
    b"z00z.consensus.dh_key.v1",
    b"z00z.consensus.owner_tag.v1",
    b"z00z.consensus.tag16.v1",
    b"z00z.consensus.asset_id.v1",
    b"z00z.consensus.leaf_ad.v1",
    b"z00z.consensus.leaf_hash.v1",
    b"z00z.consensus.pack_key.v1",
    b"z00z.consensus.pack_nonce.v1",
    b"z00z.consensus.pack_flow.v1",
    b"z00z.consensus.pack_mac.v1",
    b"z00z.consensus.xof_block.v1",
    b"z00z.consensus.tx_digest.v1",
    b"z00z.consensus.range_ctx.v1",
    b"z00z.consensus.ephemeral_scalar.v1",
];

pub const WALLET_DOMAINS: &[&[u8]] = &[b"WALLET/SEED", b"WALLET/DB_ID", b"WALLET/CACHE"];

pub const ALL_DOMAINS: &[&[u8]] = &[
    b"z00z.consensus.receiver_id.v1",
    b"z00z.consensus.view_key.v1",
    b"Z00Z/IDENTITY",
    b"z00z.consensus.dh_key.v1",
    b"z00z.consensus.owner_tag.v1",
    b"z00z.consensus.tag16.v1",
    b"z00z.consensus.asset_id.v1",
    b"z00z.consensus.leaf_ad.v1",
    b"z00z.consensus.leaf_hash.v1",
    b"z00z.consensus.pack_key.v1",
    b"z00z.consensus.pack_nonce.v1",
    b"z00z.consensus.pack_flow.v1",
    b"z00z.consensus.pack_mac.v1",
    b"z00z.consensus.xof_block.v1",
    b"z00z.consensus.tx_digest.v1",
    b"z00z.consensus.range_ctx.v1",
    b"z00z.consensus.ephemeral_scalar.v1",
    b"WALLET/SEED",
    b"WALLET/DB_ID",
    b"WALLET/CACHE",
];
