impl<
        Sec,
        K,
        Addr,
        WStorage,
        Assets,
        Txs,
        Receipts,
        Sel,
        Fee,
        Asm,
        Sig,
        Prover,
        Ver,
        BackupExp,
        BackupImp,
        Pol,
    >
    Z00ZWallet<
        Sec,
        K,
        Addr,
        WStorage,
        Assets,
        Txs,
        Receipts,
        Sel,
        Fee,
        Asm,
        Sig,
        Prover,
        Ver,
        BackupExp,
        BackupImp,
        Pol,
    >
where
    Sec: SecretStore,
    K: KeyManager,
    Addr: ReceiverManager,
    WStorage: WalletStorage,
    Assets: AssetStorage,
    Txs: TxStorage,
    Receipts: ReceiptStorage,
    Sel: AssetSelector,
    Fee: FeeEstimator,
    Asm: TxAssembler,
    Sig: Signer,
    Prover: self::Prover,
    Ver: LocalVerifier,
    BackupExp: BackupExporter,
    BackupImp: BackupImporter,
    Pol: Policy,
{
    /// Create a new wallet from injected components.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        wallet_id: WalletId,
        chain_id: ChainId,
        secret_store: Sec,
        key_manager: K,
        receiver_manager: Addr,
        wallet_storage: WStorage,
        asset_storage: Assets,
        tx_storage: Txs,
        receipt_storage: Receipts,
        asset_selector: Sel,
        fee_estimator: Fee,
        tx_assembler: Asm,
        signer: Sig,
        prover: Prover,
        local_verifier: Ver,
        backup_exporter: BackupExp,
        backup_importer: BackupImp,
        policy: Pol,
        state: WalletState,
    ) -> Self {
        Self {
            kernel: WalletKernel::new(wallet_id, chain_id),
            secret_store,
            key_manager,
            receiver_manager,
            wallet_storage,
            asset_storage,
            tx_storage,
            receipt_storage,
            asset_selector,
            fee_estimator,
            tx_assembler,
            signer,
            prover,
            local_verifier,
            backup_exporter,
            backup_importer,
            policy,
            state: Arc::new(RwLock::new(state)),
        }
    }
}