#![allow(unexpected_cfgs)]
#![cfg(kani)]

// GENERATED BY z00z-verification-artifact-builder
#[kani::proof]
fn generated_checkpoint_artifact_id_stable() {
    let artifact = z00z_storage::fixture_support::checkpoint_fixtures::artifact();
    let first =
        z00z_storage::checkpoint::derive_checkpoint_id(&artifact).expect("derive checkpoint id");
    let second =
        z00z_storage::checkpoint::derive_checkpoint_id(&artifact).expect("derive checkpoint id");
    assert_eq!(first, second);
}

#[kani::proof]
fn generated_checkpoint_draft_id_stable() {
    let draft = z00z_storage::fixture_support::checkpoint_fixtures::draft();
    let first =
        z00z_storage::checkpoint::derive_draft_id(&draft).expect("derive checkpoint draft id");
    let second =
        z00z_storage::checkpoint::derive_draft_id(&draft).expect("derive checkpoint draft id");
    assert_eq!(first, second);
}

#[kani::proof]
fn test_exec_id_is_stable() {
    let first = z00z_storage::checkpoint::derive_exec_id(b"exec-input-v1");
    let second = z00z_storage::checkpoint::derive_exec_id(b"exec-input-v1");
    assert_eq!(first, second);
}

#[kani::proof]
fn test_exec_id_changes_input() {
    let first = z00z_storage::checkpoint::derive_exec_id(b"exec-input-v1");
    let second = z00z_storage::checkpoint::derive_exec_id(b"exec-input-v2");
    assert_ne!(first, second);
}
