- key: home
  path: /home
  title: Home
  translateKey: nav.home
  icon: home-icon
  type: ITEM
  authority: []
  meta:
    description:
      translateKey: nav.chatDesc  
      label: Landing Page
  subMenu: []

- key: md-plugins-test
  path: /md-plugins-test
  title: Md Plugins Test
  translateKey: nav.md-plugins-test
  icon: concepts
  type: ITEM
  authority: []
  meta:
    description:
      translateKey: nav.md-plugins-test  
      label: MD Plugins Test
  subMenu: []

- key: themes-demo
  path: /themes-demo
  title: Themes Demo
  translateKey: nav.themes-demo.md
  icon: concepts
  type: ITEM
  authority: []
  meta:
    description:
      translateKey: nav.themes-demo.md  
      label: Themes Demo
  subMenu: []

- key: emoji
  path: /emoji
  title: Emoji Test
  translateKey: nav.emoji
  icon: ai-chat
  type: ITEM
  authority: []
  meta:
    description:
      translateKey: nav.chatDesc  
      label: Landing Page
  subMenu: []

- key: plugins-test
  path: /plugins-test
  title: Plugins Test
  translateKey: nav.plugins-test
  icon: home-icon
  type: ITEM
  authority: []
  meta:
    description:
      translateKey: nav.chatDesc  
      label: Landing Page
  subMenu: []

- key: code-highlight-test
  path: /code-highlight-test
  title: Code Highlight Test
  translateKey: nav.code-highlight-test
  icon: home-icon
  type: ITEM
  authority: []
  meta:
    description:
      translateKey: nav.chatDesc  
      label: Landing Page
  subMenu: []  

- key: test
  path: /test
  title: Test
  translateKey: nav.test
  icon: tests-icon
  type: ITEM
  authority: []
  meta:
    description:
      translateKey: nav.chatDesc  
      label: Test Page
  subMenu: [] 

# - key: vaults
#   path: ""
#   title: Vaults
#   translateKey: nav.vaults
#   icon: vaults
#   type: COLLAPSE
#   authority: []
#   subMenu:
#     - key: vaults.create
#       path: /vaults/create
#       title: Create
#       translateKey: nav.vaults.create
#       type: ITEM
#       authority: []
#       subMenu: []
#       icon: create-icon

#     - key: vaults.status
#       path: /vaults/status
#       title: Status
#       translateKey: nav.vaults.status
#       type: ITEM
#       authority: []
#       subMenu: []
#       icon: status-icon

# - key: monitors
#   path: ""
#   title: Monitors
#   translateKey: nav.monitors
#   icon: monitors-icon
#   type: COLLAPSE
#   authority: []
#   subMenu:
#     - key: monitors.network
#       path: /monitors/network
#       title: Network
#       translateKey: nav.monitors.network
#       type: ITEM
#       authority: []
#       subMenu: []
#       icon: network-icon

#     - key: monitors.stats
#       path: /monitors/stats
#       title: Statistics
#       translateKey: nav.monitors.stats
#       type: ITEM
#       authority: []
#       subMenu: []
#       icon: statistics-icon

# - key: validators
#   path: ""
#   title: Validators
#   translateKey: nav.validators
#   icon: validators
#   type: COLLAPSE
#   authority: []
#   subMenu:
#     - key: validators.dashboard
#       path: /validators/dashboard
#       title: Dashboard
#       translateKey: nav.validators.dashboard
#       type: ITEM
#       authority: []
#       subMenu: []
#       icon: dashboard-icon

#     - key: validators.voting
#       path: /validators/voting
#       title: Voting
#       translateKey: nav.validators.voting
#       type: ITEM
#       authority: []
#       subMenu: []
#       icon: voting-icon

#     - key: validators.tests
#       path: /validators/tests
#       title: Tests
#       translateKey: nav.validators.tests
#       type: ITEM
#       authority: []
#       subMenu: []
#       icon: tests-icon

- key: dao
  path: ""
  title: DAO
  translateKey: nav.dao
  icon: dao-icon
  type: COLLAPSE
  authority: []
  meta:
    description:
      translateKey: nav.dao.daoDesc
      label: Decentralized governance
  subMenu:
    - key: dao.structure
      path: /dao/structure
      title: Structure
      translateKey: nav.dao.structure
      icon: structure-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.dao.structureDesc
          label: Organization hierarchy
      subMenu: []

    - key: dao.governance
      path: /dao/governance
      title: Governance
      translateKey: nav.dao.governance
      icon: governance-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.dao.governanceDesc
          label: Proposals and voting
      subMenu: []

- key: legal-and-compliance
  path: ""
  title: Legal & Compliance
  translateKey: nav.Legal
  icon: law
  type: COLLAPSE
  authority: []
  meta:
    description:
      translateKey: nav.legal.legalDesc
      label: Legal
  subMenu:
    - key: legal-and-compliance.legal-doc
      path: /legal-and-compliance/legal-doc
      title: Legal Doc
      translateKey: nav.legal.legal
      icon: legal-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.legal.legal
          label: Create new Legal Doc
      subMenu: []

- key: documentation
  path: ""
  title: Documentation
  translateKey: nav.documentation
  icon: documentation
  type: COLLAPSE
  authority: []
  meta:
    description:
      translateKey: nav.documentationDesc
      label: Technical documentation
  subMenu:
    - key: documentation.installation
      path: /documentation/installation
      title: Installation
      translateKey: nav.documentation.installation
      icon: installation-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.documentation.installationDesc
          label: Setup instructions
      subMenu: []

    - key: documentation.vault-file-structure
      path: /documentation/vault-file-structure
      title: Vault File Structure
      translateKey: nav.documentation.vault-file-structure
      icon: universal
      type: ITEM
      authority: []
      meta:
      description:
        translateKey: nav.documentation.vault-file-structure
      subMenu: []

    - key: documentation.protocol
      path: /documentation/protocol
      title: Protocol
      translateKey: nav.documentation.protocol
      icon: protocol-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.documentation.protocolDesc
          label: Technical specifications
      subMenu: []

    - key: documentation.privacy
      path: /documentation/privacy
      title: Privacy
      translateKey: nav.documentation.privacy
      icon: privacy-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.documentation.PrivacyDesc
          label: Privacy
      subMenu: []

    - key: documentation.api
      path: /documentation/api
      title: API
      translateKey: nav.documentation.api
      icon: api-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.documentation.api
          label: API
      subMenu: []

    - key: documentation.sdk
      path: /documentation/sdk
      title: SDK
      translateKey: nav.documentation.sdk
      icon: sdk-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.documentation.sdkDesc
          label: Privacy
      subMenu: []

- key: help-center
  path: ""
  title: Help Center
  translateKey: nav.helpCenter
  icon: help-center-icon
  type: COLLAPSE
  authority: []
  meta:
    description:
      translateKey: nav.helpCenter.helpCenterDesc
      label: Support and articles
  subMenu:
    - key: help-center.tutorial
      path: /help-center/tutorial
      title: Tutorial
      translateKey: nav.helpCenter.tutorial
      icon: tutorial-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.helpCenter.tutorial
          label: Central support hub
      subMenu: []

    - key: help-center.userGuide
      path: /help-center/user-guide
      title: User Guide
      translateKey: nav.helpCenter.userGuide
      icon: userguide-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.helpCenter.userGuide
          label: Central support hub
      subMenu: []

    - key: help-center.FAQ
      path: /help-center/faqs
      title: FAQ
      translateKey: nav.helpCenter.FAQ
      icon: faq-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.helpCenter.FAQ
          label: Central support hub
      subMenu: []

    - key: help-center.examples
      path: /help-center/examples
      title: Examples
      translateKey: nav.helpCenter.examples
      icon: examples-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.helpCenter.examples
          label: Central support hub
      subMenu: []

    - key: help-center.useCases
      path: /help-center/use-cases
      title: Use Cases
      translateKey: nav.helpCenter.useCases
      icon: usecases-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.helpCenter.useCases
          label: Central support hub
      subMenu: []

    - key: help-center.zuz-dsl
      path: /help-center/zuz-dsl
      title: Zuz Dsl
      translateKey: nav.helpCenter.zuz-dsl
      icon: zuzdsl-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.helpCenter.zuz-dsl
          label: Central support hub
      subMenu: []

- key: about
  path: ""
  title: About
  translateKey: nav.About
  icon: about
  type: COLLAPSE
  authority: []
  meta:
    description:
      translateKey: nav.about.aboutDesc
      label: About
  subMenu:
    - key: about.about
      path: /about/about-doc
      title: About Doc
      translateKey: nav.about.about
      icon: about-icon
      type: ITEM
      authority: []
      meta:
        description:
          translateKey: nav.about.about
          label: Create new About Docs
      subMenu: []
