version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  kroki:
    image: yuzutech/kroki
    ports:
      - "8000:8000"
    # Uncomment the following lines if you need to use extra diagrams types
    # depends_on:
    #   - excalidraw
    # environment:
    #   - KROKI_EXCALIDRAW_HOST=excalidraw
    # If you do need to explicitly mount /tmp, make sure to include the exec option
    tmpfs:
      - /tmp:exec

  # excalidraw:
  #   image: yuzutech/kroki-excalidraw
  #   expose:
  #     - "8004"
