import type { Config } from 'tailwindcss'

const config: Config = {
    content: [
        './src/assets/svg/**/*.{js,ts,jsx,tsx,mdx}',
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/constants/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/utils/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    darkMode: 'class',
    theme: {
        fontFamily: {
            sans: [
                'Inter',
                'ui-sans-serif',
                'system-ui',
                '-apple-system',
                'BlinkMacSystemFont',
                '"Segoe UI"',
                'Roboto',
                '"Helvetica Neue"',
                'Arial',
                '"Noto Sans"',
                'sans-serif',
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            serif: [
                'ui-serif',
                'Georgia',
                'Cambria',
                '"Times New Roman"',
                'Times',
                'serif',
            ],
            mono: [
                'ui-monospace',
                'SFMono-Regular',
                'Menlo',
                'Monaco',
                'Consolas',
                '"Liberation Mono"',
                '"Courier New"',
                'monospace',
            ],
        },
        screens: {
            xs: '576px',
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            '2xl': '1536px',
        },
        extend: {
            colors: {
                primary: 'var(--primary)',
                'primary-deep': 'var(--primary-deep)',
                'primary-mild': 'var(--primary-mild)',
                'primary-subtle': 'var(--primary-subtle)',
                error: 'var(--error)',
                'error-subtle': 'var(--error-subtle)',
                success: 'var(--success)',
                'success-subtle': 'var(--success-subtle)',
                info: 'var(--info)',
                'info-subtle': 'var(--info-subtle)',
                warning: 'var(--warning)',
                'warning-subtle': 'var(--warning-subtle)',
                neutral: 'var(--neutral)',
                'gray-50': 'var(--gray-50)',
                'gray-100': 'var(--gray-100)',
                'gray-200': 'var(--gray-200)',
                'gray-300': 'var(--gray-300)',
                'gray-400': 'var(--gray-400)',
                'gray-500': 'var(--gray-500)',
                'gray-600': 'var(--gray-600)',
                'gray-700': 'var(--gray-700)',
                'gray-800': 'var(--gray-800)',
                'gray-900': 'var(--gray-900)',
                'gray-950': 'var(--gray-950)',
                background: 'var(--background)',
                'header-background': 'var(--header-background)',
                'header-hover-background': 'var(--header-hover-background)',
                'header-hover-text': 'var(--header-hover-text)',
                'side-nav-background': 'var(--side-nav-background)',
                'side-nav-border': 'var(--side-nav-border)',
                'stacked-side-nav-mini-background':
                    'var(--stacked-side-nav-mini-background)',
                'stacked-side-nav-mini-border':
                    'var(--stacked-side-nav-mini-border)',
                'stacked-side-nav-secondary-background':
                    'var(--stacked-side-nav-secondary-background)',
                'stacked-side-nav-secondary-border':
                    'var(--stacked-side-nav-secondary-border)',
                'menu-item-text': 'var(--menu-item-text)',
                'menu-item-hover-text': 'var(--menu-item-hover-text)',
                'menu-item-hover-background':
                    'var(--menu-item-hover-background)',
                'menu-item-border': 'var(--menu-item-border)',
                'menu-collapse-item-text': 'var(--menu-collapse-item-text)',
                'menu-collapse-item-hover-text':
                    'var(--menu-collapse-item-hover-text)',
                'menu-collapse-item-hover-background':
                    'var(--menu-collapse-item-hover-background)',
                'drawer-background': 'var(--drawer-background)',
                'drawer-border': 'var(--drawer-border)',
                'drawer-overlay': 'var(--drawer-overlay)',
                'search-dialog-border': 'var(--search-dialog-border)',
                'search-dialog-input-text': 'var(--search-dialog-input-text)',
                'search-item-hover-background':
                    'var(--search-item-hover-background)',
                'search-item-text': 'var(--search-item-text)',
                'heading-1': 'var(--heading-1)',
                'heading-2': 'var(--heading-2)',
                'heading-3': 'var(--heading-3)',
                'heading-4': 'var(--heading-4)',
                'heading-5': 'var(--heading-5)',
                'heading-6': 'var(--heading-6)',
                paragraph: 'var(--paragraph)',
                hr: 'var(--hr)',
                small: 'var(--small)',
                strong: 'var(--strong)',
                b: 'var(--b)',
                em: 'var(--em)',
                i: 'var(--i)',
                u: 'var(--u)',
                mark: 'var(--mark)',
                del: 'var(--del)',
                ins: 'var(--ins)',
                sub: 'var(--sub)',
                sup: 'var(--sup)',
                'avatar-background': 'var(--avatar-background)',
                'avatar-text': 'var(--avatar-text)',
                'card-background': 'var(--card-background)',
                'card-border': 'var(--card-border)',
                'dialog-background': 'var(--dialog-background)',
                'dialog-overlay': 'var(--dialog-overlay)',
                'dropdown-background': 'var(--dropdown-background)',
                'dropdown-border': 'var(--dropdown-border)',
                'input-background': 'var(--input-background)',
                'input-border': 'var(--input-border)',
                'input-text': 'var(--input-text)',
                'input-placeholder': 'var(--input-placeholder)',
                'input-addon-background': 'var(--input-addon-background)',
                'input-addon-border': 'var(--input-addon-border)',
                'notification-background': 'var(--notification-background)',
                'notification-border': 'var(--notification-border)',
                'notification-text': 'var(--notification-text)',
                'notification-item-background-hover':
                    'var(--notification-item-background-hover)',
                'notification-item-background-active':
                    'var(--notification-item-background-active)',
                'notification-item-background-border':
                    'var(--notification-item-background-border)',
                'notification-item-badge-background-readed':
                    'var(--notification-item-badge-background-readed)',
                'radio-border': 'var(--radio-border)',
                'radio-ring': 'var(--radio-ring)',
                'radio-disabled-background': 'var(--radio-disabled-background)',
                'radio-disabled-text': 'var(--radio-disabled-text)',
                'radio-disabled-ring': 'var(--radio-disabled-ring)',
                'radio-disabled-border': 'var(--radio-disabled-border)',
                'select-background': 'var(--select-background)',
                'select-border': 'var(--select-border)',
                'select-text': 'var(--select-text)',
                'select-single-value-text': 'var(--select-single-value-text)',
                'select-multi-value-background':
                    'var(--select-multi-value-background)',
                'select-multi-value-text': 'var(--select-multi-value-text)',
                'select-multi-value-border': 'var(--select-multi-value-border)',
                'select-menu-background': 'var(--select-menu-background)',
                'select-menu-border': 'var(--select-menu-border)',
                'select-menu-ring': 'var(--select-menu-ring)',
                'select-option-hover-text': 'var(--select-option-hover-text)',
                'table-border': 'var(--table-border)',
                'table-header-background': 'var(--table-header-background)',
                'table-header-text': 'var(--table-header-text)',
                'table-header-border': 'var(--table-header-border)',
                'table-body-border': 'var(--table-body-border)',
                'table-footer-border': 'var(--table-footer-border)',
                'table-row-background-hover':
                    'var(--table-row-background-hover)',
                'collapsible-background': 'var(--collapsible-background)',
                'collapsible-text': 'var(--collapsible-text)',
                'collapsible-border': 'var(--collapsible-border)',
                'toc-title-text': 'var(--toc-title-text)',
                'toc-background': 'var(--toc-background)',
                'toc-border': 'var(--toc-border)',
                'toc-title-text-dark': 'var(--toc-title-text-dark)',
                'toc-background-dark': 'var(--toc-background-dark)',
                'toc-border-dark': 'var(--toc-border-dark)',
                'button-default-background': 'var(--button-default-background)',
                'button-default-border': 'var(--button-default-border)',
                'button-default-text': 'var(--button-default-text)',
                'button-default-active-border':
                    'var(--button-default-active-border)',
                'markdown-demo-code-background':
                    'var(--markdown-demo-code-background)',
                'markdown-demo-code-copy-button-hover-background':
                    'var(--markdown-demo-code-copy-button-hover-background)',
                'markdown-demo-border': 'var(--markdown-demo-border)',
                'markdown-tabs-border': 'var(--markdown-tabs-border)',
                'markdown-tabs-text': 'var(--markdown-tabs-text)',
                'markdown-note-bg': 'var(--markdown-note-bg)',
                'markdown-note-border': 'var(--markdown-note-border)',
                'markdown-note-text': 'var(--markdown-note-text)',
                'markdown-note-mark-bg': 'var(--markdown-note-mark-bg)',
                'markdown-note-mark-text': 'var(--markdown-note-mark-text)',
                'markdown-important-bg': 'var(--markdown-important-bg)',
                'markdown-important-border': 'var(--markdown-important-border)',
                'markdown-important-text': 'var(--markdown-important-text)',
                'markdown-important-mark-bg':
                    'var(--markdown-important-mark-bg)',
                'markdown-important-mark-text':
                    'var(--markdown-important-mark-text)',
                'markdown-tip-bg': 'var(--markdown-tip-bg)',
                'markdown-tip-border': 'var(--markdown-tip-border)',
                'markdown-tip-text': 'var(--markdown-tip-text)',
                'markdown-tip-mark-bg': 'var(--markdown-tip-mark-bg)',
                'markdown-tip-mark-text': 'var(--markdown-tip-mark-text)',
                'markdown-warning-bg': 'var(--markdown-warning-bg)',
                'markdown-warning-border': 'var(--markdown-warning-border)',
                'markdown-warning-text': 'var(--markdown-warning-text)',
                'markdown-warning-mark-bg': 'var(--markdown-warning-mark-bg)',
                'markdown-warning-mark-text':
                    'var(--markdown-warning-mark-text)',
                'markdown-caution-bg': 'var(--markdown-caution-bg)',
                'markdown-caution-border': 'var(--markdown-caution-border)',
                'markdown-caution-text': 'var(--markdown-caution-text)',
                'markdown-caution-mark-bg': 'var(--markdown-caution-mark-bg)',
                'markdown-caution-mark-text':
                    'var(--markdown-caution-mark-text)',
                'markdown-task-border': 'var(--markdown-task-border)',
                'markdown-task-checkmark-color':
                    'var(--markdown-task-checkmark-color)',
            },
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            typography: (theme: any) => ({
                DEFAULT: {
                    css: {
                        color: theme('colors.gray.500'),
                        maxWidth: '65ch',
                    },
                },
                invert: {
                    css: {
                        color: theme('colors.gray.400'),
                    },
                },
            }),
        },
    },
    plugins: [
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        require('@tailwindcss/typography'),
    ],
}
export default config
