#![allow(unexpected_cfgs)]
#![cfg(kani)]

// GENERATED BY z00z-verification-artifact-builder
#[path = "fixtures/generated_kani/generated_kani_compact.rs"]
mod fixtures;

#[kani::proof]
fn test_compact_roundtrip_stable() {
    let decoded =
        z00z_wallets::receiver::request::decode_request_compact(fixtures::SAMPLE_REQUEST_COMPACT)
            .expect("decode compact request");
    let reencoded = z00z_wallets::receiver::request::encode_request_compact(&decoded);
    assert_eq!(reencoded, fixtures::SAMPLE_REQUEST_COMPACT);
}
