#![allow(unexpected_cfgs)]
#![cfg(kani)]

// GENERATED BY z00z-verification-artifact-builder
#[path = "fixtures/generated_kani/generated_kani_compact.rs"]
mod fixtures;

#[kani::proof]
fn test_card_record_roundtrip() {
    let decoded = z00z_wallets::chain::ReceiverCardRecord::from_compact(
        fixtures::SAMPLE_RECORD_COMPACT,
        None,
    )
    .expect("decode compact receiver record");
    let reencoded = decoded
        .to_compact()
        .expect("reencode compact receiver record");
    assert_eq!(reencoded, fixtures::SAMPLE_RECORD_COMPACT);
}
