#!/bin/bash

set -euo pipefail

Z00Z_VERIFY_ENV_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
Z00Z_VERIFY_ENV_ROOT_DIR="$(cd "$Z00Z_VERIFY_ENV_SCRIPT_DIR/.." && pwd)"
Z00Z_VERIFY_ENV_TOOLS_DIR="${Z00Z_VERIFY_TOOLS_DIR:-$Z00Z_VERIFY_ENV_ROOT_DIR/tools/formal_verification}"
Z00Z_VERIFY_ENV_VERSIONS_ENV="$Z00Z_VERIFY_ENV_ROOT_DIR/scripts/verification-tools/versions.env"

if [[ -f "$Z00Z_VERIFY_ENV_VERSIONS_ENV" ]]; then
  # shellcheck source=/dev/null
  source "$Z00Z_VERIFY_ENV_VERSIONS_ENV"
fi

Z00Z_VERIFY_ENV_PATH_DIRS=(
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/saw-suite/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/cargo/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/python/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/node/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/opam/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/prusti/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/verus/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/tamarin/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/maude/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/apalache/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/alloy/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/saw/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/cryptol/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/cvc5/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/bitwuzla/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/mir-json/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/charon/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/aeneas/bin"
  "$Z00Z_VERIFY_ENV_TOOLS_DIR/rg/bin"
)

for ((z00z_verify_env_idx=${#Z00Z_VERIFY_ENV_PATH_DIRS[@]} - 1; z00z_verify_env_idx >= 0; z00z_verify_env_idx--)); do
  z00z_verify_env_dir="${Z00Z_VERIFY_ENV_PATH_DIRS[$z00z_verify_env_idx]}"
  if [[ -d "$z00z_verify_env_dir" ]]; then
    PATH="$z00z_verify_env_dir:$PATH"
  fi
done

export PATH
export CARGO_HOME="${Z00Z_VERIFY_CARGO_HOME:-$Z00Z_VERIFY_ENV_TOOLS_DIR/cargo}"
export RUSTUP_HOME="${Z00Z_RUSTUP_HOME:-$Z00Z_VERIFY_ENV_TOOLS_DIR/rustup}"
export RUSTUP_TOOLCHAIN="${Z00Z_RUSTUP_TOOLCHAIN:-stable}"
export KANI_HOME="${Z00Z_KANI_HOME:-$Z00Z_VERIFY_ENV_TOOLS_DIR/kani}"
export NPM_CONFIG_PREFIX="${Z00Z_VERIFY_NODE_PREFIX:-$Z00Z_VERIFY_ENV_TOOLS_DIR/node}"
export Z00Z_OPAM_ROOT="${Z00Z_OPAM_ROOT:-$Z00Z_VERIFY_ENV_TOOLS_DIR/opam/root}"
export Z00Z_VERIFY_OPAM_SWITCH="${Z00Z_VERIFY_OPAM_SWITCH:-z00z-verify}"
export CREUSOT_DATA_HOME="${Z00Z_CREUSOT_DATA_HOME:-$Z00Z_VERIFY_ENV_TOOLS_DIR/creusot/data}"
export XDG_CONFIG_HOME="${Z00Z_CREUSOT_CONFIG_HOME:-$Z00Z_VERIFY_ENV_TOOLS_DIR/creusot/config}"
export XDG_CACHE_HOME="${Z00Z_CREUSOT_CACHE_HOME:-$Z00Z_VERIFY_ENV_TOOLS_DIR/creusot/cache}"
export RUFF_CACHE_DIR="${Z00Z_RUFF_CACHE_DIR:-$Z00Z_VERIFY_ENV_TOOLS_DIR/python/ruff-cache}"
export UV_CACHE_DIR="${Z00Z_UV_CACHE_DIR:-$Z00Z_VERIFY_ENV_TOOLS_DIR/python/uv-cache}"
export MIRI_SYSROOT="${Z00Z_MIRI_SYSROOT:-$Z00Z_VERIFY_ENV_TOOLS_DIR/miri/sysroot}"

if [[ -d "$Z00Z_VERIFY_ENV_TOOLS_DIR/saw-suite/rlibs" ]]; then
  export CRUX_RUST_LIBRARY_PATH="${CRUX_RUST_LIBRARY_PATH:-$Z00Z_VERIFY_ENV_TOOLS_DIR/saw-suite/rlibs}"
  export SAW_RUST_LIBRARY_PATH="${SAW_RUST_LIBRARY_PATH:-$Z00Z_VERIFY_ENV_TOOLS_DIR/saw-suite/rlibs}"
elif [[ -d "$Z00Z_VERIFY_ENV_TOOLS_DIR/mir-json/rlibs" ]]; then
  export CRUX_RUST_LIBRARY_PATH="${CRUX_RUST_LIBRARY_PATH:-$Z00Z_VERIFY_ENV_TOOLS_DIR/mir-json/rlibs}"
  export SAW_RUST_LIBRARY_PATH="${SAW_RUST_LIBRARY_PATH:-$Z00Z_VERIFY_ENV_TOOLS_DIR/mir-json/rlibs}"
fi

if [[ -x "$Z00Z_VERIFY_ENV_TOOLS_DIR/saw-suite/bin/crux-mir" ]]; then
  export CRUX_MIR="${CRUX_MIR:-$Z00Z_VERIFY_ENV_TOOLS_DIR/saw-suite/bin/crux-mir}"
elif [[ -x "$Z00Z_VERIFY_ENV_TOOLS_DIR/saw-suite/bin/crux-mir-comp" ]]; then
  export CRUX_MIR="${CRUX_MIR:-$Z00Z_VERIFY_ENV_TOOLS_DIR/saw-suite/bin/crux-mir-comp}"
fi

export Z00Z_CARGO_PROFILE_ARGS="${Z00Z_CARGO_PROFILE_ARGS:---release}"
export Z00Z_DISABLE_TIME_LIMITS="${Z00Z_DISABLE_TIME_LIMITS:-1}"
export Z00Z_RELEASE_BLOCK_UNKNOWN="${Z00Z_RELEASE_BLOCK_UNKNOWN:-1}"
export Z00Z_L0_STRICT="${Z00Z_L0_STRICT:-$Z00Z_RELEASE_BLOCK_UNKNOWN}"
export Z00Z_L1_STRICT="${Z00Z_L1_STRICT:-$Z00Z_RELEASE_BLOCK_UNKNOWN}"
export Z00Z_L2_STRICT="${Z00Z_L2_STRICT:-$Z00Z_RELEASE_BLOCK_UNKNOWN}"
export Z00Z_L3_STRICT="${Z00Z_L3_STRICT:-$Z00Z_RELEASE_BLOCK_UNKNOWN}"
export Z00Z_L4_STRICT="${Z00Z_L4_STRICT:-$Z00Z_RELEASE_BLOCK_UNKNOWN}"
export Z00Z_REQUIRE_PROOF_FOR_CRITICAL="${Z00Z_REQUIRE_PROOF_FOR_CRITICAL:-1}"
export Z00Z_REQUIRE_FUZZ_FOR_PARSER="${Z00Z_REQUIRE_FUZZ_FOR_PARSER:-1}"
export Z00Z_REQUIRE_CRYPTO_REVIEW_FOR_NEW_PRIMITIVE="${Z00Z_REQUIRE_CRYPTO_REVIEW_FOR_NEW_PRIMITIVE:-1}"
export CARGO_HTTP_MULTIPLEXING="${Z00Z_CARGO_HTTP_MULTIPLEXING:-false}"
export CARGO_NET_RETRY="${Z00Z_CARGO_NET_RETRY:-10}"
export CARGO_REGISTRIES_CRATES_IO_PROTOCOL="${Z00Z_CARGO_REGISTRIES_CRATES_IO_PROTOCOL:-sparse}"
