//! RPC method definitions
//!
//! - wallet.* - 15 methods
//! - asset.* - 13 methods
//! - object.* - 14 methods
//! - tx.* - 12 methods
//! - key.* - 6 methods
//! - backup.* - 4 methods
//! - scan.* - 4 methods
//! - chain.* - 3 methods
//! - storage.* - 3 methods
//! - network.* - 2 methods

// Trait definitions (generated by jsonrpsee #[rpc] macro)
#[path = "app_rpc.rs"]
pub mod app_rpc;
#[path = "asset_rpc.rs"]
pub mod asset_rpc;
#[path = "backup_rpc.rs"]
pub mod backup_rpc;
#[path = "chain_rpc.rs"]
pub mod chain_rpc;
#[path = "key_rpc.rs"]
pub mod key_rpc;
#[path = "network_rpc.rs"]
pub mod network_rpc;
#[path = "object_rpc.rs"]
pub mod object_rpc;
#[path = "storage_rpc.rs"]
pub mod storage_rpc;
#[path = "tx_rpc.rs"]
pub mod tx_rpc;
#[path = "wallet_rpc.rs"]
pub mod wallet_rpc;

// Server-side implementations for the current RPC surface.
#[cfg(not(target_arch = "wasm32"))]
#[path = "app_rpc_impl.rs"]
pub mod app_rpc_impl;

#[cfg(not(target_arch = "wasm32"))]
#[path = "asset_rpc_impl.rs"]
pub mod asset_rpc_impl;

#[cfg(not(target_arch = "wasm32"))]
#[path = "asset_rpc_balance.rs"]
pub mod asset_rpc_balance;

#[cfg(not(target_arch = "wasm32"))]
#[path = "asset_rpc_caches.rs"]
pub mod asset_rpc_caches;

#[cfg(not(target_arch = "wasm32"))]
#[path = "asset_quarantine.rs"]
pub mod asset_quarantine;

#[cfg(not(target_arch = "wasm32"))]
#[path = "asset_rpc_rate_limits.rs"]
pub mod asset_rpc_rate_limits;

#[cfg(not(target_arch = "wasm32"))]
#[path = "asset_rpc_registry.rs"]
pub mod asset_rpc_registry;

#[cfg(not(target_arch = "wasm32"))]
#[path = "asset_rpc_stakes.rs"]
pub mod asset_rpc_stakes;

#[cfg(not(target_arch = "wasm32"))]
#[path = "backup_rpc_impl.rs"]
pub mod backup_rpc_impl;

#[cfg(not(target_arch = "wasm32"))]
#[path = "chain_rpc_impl.rs"]
pub mod chain_rpc_impl;

#[cfg(not(target_arch = "wasm32"))]
#[path = "key_rpc_impl.rs"]
pub mod key_rpc_impl;

#[cfg(not(target_arch = "wasm32"))]
#[path = "network_rpc_impl.rs"]
pub mod network_rpc_impl;

#[cfg(not(target_arch = "wasm32"))]
#[path = "object_rpc_impl.rs"]
pub mod object_rpc_impl;

#[cfg(not(target_arch = "wasm32"))]
#[path = "asset_ownership_check.rs"]
pub mod ownership_check;

#[cfg(not(target_arch = "wasm32"))]
#[path = "storage_rpc_impl.rs"]
pub mod storage_rpc_impl;

#[cfg(not(target_arch = "wasm32"))]
#[path = "tx_rpc_impl.rs"]
pub mod tx_rpc_impl;

#[cfg(not(target_arch = "wasm32"))]
#[path = "tx_rpc_broadcast.rs"]
pub mod tx_rpc_broadcast;

#[cfg(not(target_arch = "wasm32"))]
#[path = "tx_rpc_admission.rs"]
pub mod tx_rpc_admission;

#[cfg(not(target_arch = "wasm32"))]
#[path = "tx_rpc_idempotency.rs"]
pub mod tx_rpc_idempotency;

#[cfg(not(target_arch = "wasm32"))]
#[path = "tx_rpc_support.rs"]
pub mod tx_rpc_support;

#[cfg(not(target_arch = "wasm32"))]
#[path = "tx_rpc_rate_limits.rs"]
pub mod tx_rpc_rate_limits;

#[cfg(not(target_arch = "wasm32"))]
#[path = "tx_runtime_state.rs"]
pub mod tx_runtime_state;

#[cfg(not(target_arch = "wasm32"))]
#[path = "wallet_rpc_impl.rs"]
pub mod wallet_rpc_impl;

// Re-export traits generated by jsonrpsee #[rpc] macro
// The macro generates *RpcServer (for implementation) and *RpcClient (for calling)
#[cfg(not(target_arch = "wasm32"))]
pub use app_rpc::{AppRpcClient, AppRpcServer};

#[cfg(not(target_arch = "wasm32"))]
pub use asset_rpc::{AssetRpcClient, AssetRpcServer};

#[cfg(not(target_arch = "wasm32"))]
pub use backup_rpc::{BackupRpcClient, BackupRpcServer};

#[cfg(not(target_arch = "wasm32"))]
pub use chain_rpc::{ChainRpcClient, ChainRpcServer};

#[cfg(not(target_arch = "wasm32"))]
pub use chain_rpc::ChainScanRpc;

#[cfg(not(target_arch = "wasm32"))]
pub use key_rpc::{KeyRpcClient, KeyRpcServer};

#[cfg(not(target_arch = "wasm32"))]
pub use network_rpc::{NetworkRpcClient, NetworkRpcServer};

#[cfg(not(target_arch = "wasm32"))]
pub use object_rpc::{ObjectRpcClient, ObjectRpcServer};

#[cfg(not(target_arch = "wasm32"))]
pub use storage_rpc::StorageRpc;

#[cfg(not(target_arch = "wasm32"))]
pub use tx_rpc::{TxRpcClient, TxRpcServer};

#[cfg(not(target_arch = "wasm32"))]
pub use wallet_rpc::{WalletRpcClient, WalletRpcServer};

// Re-export server implementations
#[cfg(not(target_arch = "wasm32"))]
pub use app_rpc_impl::AppRpcImpl;

#[cfg(not(target_arch = "wasm32"))]
pub use asset_rpc_impl::AssetRpcImpl;

#[cfg(not(target_arch = "wasm32"))]
pub use backup_rpc_impl::BackupRpcImpl;

#[cfg(not(target_arch = "wasm32"))]
pub use chain_rpc_impl::{ChainRpcImpl, ChainScanRpcImpl};

#[cfg(not(target_arch = "wasm32"))]
pub use key_rpc_impl::KeyRpcImpl;

#[cfg(not(target_arch = "wasm32"))]
pub use network_rpc_impl::NetworkRpcImpl;

#[cfg(not(target_arch = "wasm32"))]
pub use storage_rpc_impl::StorageRpcImpl;

#[cfg(not(target_arch = "wasm32"))]
pub use tx_rpc_impl::TxRpcImpl;

#[cfg(not(target_arch = "wasm32"))]
pub use wallet_rpc_impl::WalletRpcImpl;
