#![allow(unexpected_cfgs)]
#![cfg(kani)]

// GENERATED BY z00z-verification-artifact-builder
use z00z_aggregators::{
    AggregatorId, BatchId, BatchRoute, ShardExecState, ShardExecTicket, ShardId, ShardPlacementView,
};

fn placement_view(shard_id: u16, generation: u64, aggregator_id: u16) -> ShardPlacementView {
    ShardPlacementView {
        route: BatchRoute {
            shard_id: ShardId::new(shard_id),
            routing_generation: generation,
        },
        primary_id: AggregatorId::new(aggregator_id),
        standby: Vec::new(),
        expected_journal_lineage: [0x61; 32],
    }
}

fn exec_ticket(
    batch_id: BatchId,
    shard_id: u16,
    generation: u64,
    aggregator_id: u16,
    state: ShardExecState,
) -> ShardExecTicket {
    ShardExecTicket {
        batch_id,
        placement: placement_view(shard_id, generation, aggregator_id),
        state,
    }
}

fn assert_placement_matches(
    placement: &ShardPlacementView,
    shard_id: u16,
    generation: u64,
    aggregator_id: u16,
) {
    assert_eq!(placement.route.shard_id, ShardId::new(shard_id));
    assert_eq!(placement.route.routing_generation, generation);
    assert_eq!(placement.primary_id, AggregatorId::new(aggregator_id));
    assert!(placement.standby.is_empty());
    assert_eq!(placement.expected_journal_lineage, [0x61; 32]);
}

fn assert_exec_matches(
    exec_ticket: &ShardExecTicket,
    batch_id: BatchId,
    shard_id: u16,
    generation: u64,
    aggregator_id: u16,
    state: ShardExecState,
) {
    assert_eq!(exec_ticket.batch_id, batch_id);
    assert_eq!(exec_ticket.state, state);
    assert_placement_matches(&exec_ticket.placement, shard_id, generation, aggregator_id);
}

#[kani::proof]
fn test_prefers_exec_placement() {
    let batch_id = BatchId::from_bytes([0x31; 32]);
    let fallback = placement_view(1, 7, 3);
    let exec = exec_ticket(batch_id, 1, 7, 4, ShardExecState::Running);

    let runtime_placement =
        z00z_validators::kani_runtime_placement_parts(Some(&fallback), Some(&exec))
            .expect("runtime placement");
    assert_placement_matches(runtime_placement, 1, 7, 4);

    let runtime_exec = z00z_validators::kani_runtime_exec_parts(Some(&exec)).expect("runtime exec");
    assert_exec_matches(runtime_exec, batch_id, 1, 7, 4, ShardExecState::Running);
}

#[kani::proof]
fn test_uses_attached_placement() {
    let fallback = placement_view(1, 7, 3);

    let runtime_placement = z00z_validators::kani_runtime_placement_parts(Some(&fallback), None)
        .expect("runtime placement");
    assert_placement_matches(runtime_placement, 1, 7, 3);
    assert!(z00z_validators::kani_runtime_exec_parts(None).is_none());
}
